[package]
name = "reflector"
version = "0.1.0"
authors = ["Micah Johnston <micah@photophore.systems>"]
edition = "2021"
publish = false

[dependencies]
reflector-graphics = { path = "reflector-graphics" }

[workspace]
members = [
    "reflector-graphics",
    "reflector-graphics/svg",
]
